import React from "react";
import ComponentCreator from "@docusaurus/ComponentCreator";

export default [
  {
    path: "/__docusaurus/debug",
    component: ComponentCreator("/__docusaurus/debug", "5ff"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/config",
    component: ComponentCreator("/__docusaurus/debug/config", "5ba"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/content",
    component: ComponentCreator("/__docusaurus/debug/content", "a2b"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/globalData",
    component: ComponentCreator("/__docusaurus/debug/globalData", "c3c"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/metadata",
    component: ComponentCreator("/__docusaurus/debug/metadata", "156"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/registry",
    component: ComponentCreator("/__docusaurus/debug/registry", "88c"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/routes",
    component: ComponentCreator("/__docusaurus/debug/routes", "000"),
    exact: true,
  },
  {
    path: "/docs",
    component: ComponentCreator("/docs", "ca8"),
    routes: [
      {
        path: "/docs/next",
        component: ComponentCreator("/docs/next", "785"),
        routes: [
          {
            path: "/docs/next",
            component: ComponentCreator("/docs/next", "abf"),
            routes: [
              {
                path: "/docs/next/getting-started/faqs",
                component: ComponentCreator("/docs/next/getting-started/faqs", "6ec"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/getting-started/prerequisites",
                component: ComponentCreator("/docs/next/getting-started/prerequisites", "ce3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/getting-started/quickstart",
                component: ComponentCreator("/docs/next/getting-started/quickstart", "9e3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/intro",
                component: ComponentCreator("/docs/next/intro", "7b1"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/auth/client-sdk",
                component: ComponentCreator("/docs/next/modules/auth/client-sdk", "e75"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/auth/overview",
                component: ComponentCreator("/docs/next/modules/auth/overview", "d21"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/auth/server-setup",
                component: ComponentCreator("/docs/next/modules/auth/server-setup", "057"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/auth/troubleshooting",
                component: ComponentCreator("/docs/next/modules/auth/troubleshooting", "4cb"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/email/overview",
                component: ComponentCreator("/docs/next/modules/email/overview", "dc1"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/email/providers",
                component: ComponentCreator("/docs/next/modules/email/providers", "531"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/email/template-management",
                component: ComponentCreator("/docs/next/modules/email/template-management", "151"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/logging/overview",
                component: ComponentCreator("/docs/next/modules/logging/overview", "bc3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/logging/quickstart",
                component: ComponentCreator("/docs/next/modules/logging/quickstart", "ac8"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/logging/sinks",
                component: ComponentCreator("/docs/next/modules/logging/sinks", "feb"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/rbac/examples",
                component: ComponentCreator("/docs/next/modules/rbac/examples", "bca"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/rbac/overview",
                component: ComponentCreator("/docs/next/modules/rbac/overview", "407"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/modules/rbac/policy-model",
                component: ComponentCreator("/docs/next/modules/rbac/policy-model", "cbd"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/platform-admin/portal-overview",
                component: ComponentCreator("/docs/next/platform-admin/portal-overview", "9ab"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/platform-admin/sdk-guide",
                component: ComponentCreator("/docs/next/platform-admin/sdk-guide", "d19"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/api/auth",
                component: ComponentCreator("/docs/next/reference/api/auth", "977"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/api/email",
                component: ComponentCreator("/docs/next/reference/api/email", "61e"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/api/logging",
                component: ComponentCreator("/docs/next/reference/api/logging", "a38"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/api/rbac",
                component: ComponentCreator("/docs/next/reference/api/rbac", "3bd"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/architecture",
                component: ComponentCreator("/docs/next/reference/architecture", "73d"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/reference/cli",
                component: ComponentCreator("/docs/next/reference/cli", "5e6"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/sdk-integration/configuration",
                component: ComponentCreator("/docs/next/sdk-integration/configuration", "8ca"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/sdk-integration/examples/browser",
                component: ComponentCreator("/docs/next/sdk-integration/examples/browser", "365"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/sdk-integration/examples/node",
                component: ComponentCreator("/docs/next/sdk-integration/examples/node", "91f"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/sdk-integration/installation",
                component: ComponentCreator("/docs/next/sdk-integration/installation", "033"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/next/sdk-integration/overview",
                component: ComponentCreator("/docs/next/sdk-integration/overview", "a12"),
                exact: true,
                sidebar: "defaultSidebar",
              },
            ],
          },
        ],
      },
      {
        path: "/docs",
        component: ComponentCreator("/docs", "726"),
        routes: [
          {
            path: "/docs",
            component: ComponentCreator("/docs", "9da"),
            routes: [
              {
                path: "/docs/getting-started/faqs",
                component: ComponentCreator("/docs/getting-started/faqs", "1aa"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/getting-started/prerequisites",
                component: ComponentCreator("/docs/getting-started/prerequisites", "f71"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/getting-started/quickstart",
                component: ComponentCreator("/docs/getting-started/quickstart", "03a"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/intro",
                component: ComponentCreator("/docs/intro", "8f9"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/auth/client-sdk",
                component: ComponentCreator("/docs/modules/auth/client-sdk", "e43"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/auth/overview",
                component: ComponentCreator("/docs/modules/auth/overview", "d1c"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/auth/server-setup",
                component: ComponentCreator("/docs/modules/auth/server-setup", "991"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/auth/troubleshooting",
                component: ComponentCreator("/docs/modules/auth/troubleshooting", "76b"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/email/overview",
                component: ComponentCreator("/docs/modules/email/overview", "6aa"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/email/providers",
                component: ComponentCreator("/docs/modules/email/providers", "252"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/email/template-management",
                component: ComponentCreator("/docs/modules/email/template-management", "6f1"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/logging/overview",
                component: ComponentCreator("/docs/modules/logging/overview", "1b7"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/logging/quickstart",
                component: ComponentCreator("/docs/modules/logging/quickstart", "95a"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/logging/sinks",
                component: ComponentCreator("/docs/modules/logging/sinks", "07d"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/rbac/examples",
                component: ComponentCreator("/docs/modules/rbac/examples", "bf4"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/rbac/overview",
                component: ComponentCreator("/docs/modules/rbac/overview", "94c"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/modules/rbac/policy-model",
                component: ComponentCreator("/docs/modules/rbac/policy-model", "88e"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/platform-admin/portal-overview",
                component: ComponentCreator("/docs/platform-admin/portal-overview", "f1a"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/platform-admin/sdk-guide",
                component: ComponentCreator("/docs/platform-admin/sdk-guide", "36e"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/api/auth",
                component: ComponentCreator("/docs/reference/api/auth", "c75"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/api/email",
                component: ComponentCreator("/docs/reference/api/email", "166"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/api/logging",
                component: ComponentCreator("/docs/reference/api/logging", "d48"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/api/rbac",
                component: ComponentCreator("/docs/reference/api/rbac", "0d5"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/architecture",
                component: ComponentCreator("/docs/reference/architecture", "c81"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/reference/cli",
                component: ComponentCreator("/docs/reference/cli", "6c0"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/sdk-integration/configuration",
                component: ComponentCreator("/docs/sdk-integration/configuration", "b3d"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/sdk-integration/examples/browser",
                component: ComponentCreator("/docs/sdk-integration/examples/browser", "1bd"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/sdk-integration/examples/node",
                component: ComponentCreator("/docs/sdk-integration/examples/node", "3c4"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/sdk-integration/installation",
                component: ComponentCreator("/docs/sdk-integration/installation", "949"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/docs/sdk-integration/overview",
                component: ComponentCreator("/docs/sdk-integration/overview", "cc7"),
                exact: true,
                sidebar: "defaultSidebar",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    path: "*",
    component: ComponentCreator("*"),
  },
];
