import React from "react";
import ComponentCreator from "@docusaurus/ComponentCreator";

export default [
  {
    path: "/__docusaurus/debug",
    component: ComponentCreator("/__docusaurus/debug", "5ff"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/config",
    component: ComponentCreator("/__docusaurus/debug/config", "5ba"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/content",
    component: ComponentCreator("/__docusaurus/debug/content", "a2b"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/globalData",
    component: ComponentCreator("/__docusaurus/debug/globalData", "c3c"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/metadata",
    component: ComponentCreator("/__docusaurus/debug/metadata", "156"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/registry",
    component: ComponentCreator("/__docusaurus/debug/registry", "88c"),
    exact: true,
  },
  {
    path: "/__docusaurus/debug/routes",
    component: ComponentCreator("/__docusaurus/debug/routes", "000"),
    exact: true,
  },
  {
    path: "/",
    component: ComponentCreator("/", "973"),
    routes: [
      {
        path: "/next",
        component: ComponentCreator("/next", "019"),
        routes: [
          {
            path: "/next",
            component: ComponentCreator("/next", "19e"),
            routes: [
              {
                path: "/next/getting-started/faqs",
                component: ComponentCreator("/next/getting-started/faqs", "5b3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/getting-started/prerequisites",
                component: ComponentCreator("/next/getting-started/prerequisites", "530"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/getting-started/quickstart",
                component: ComponentCreator("/next/getting-started/quickstart", "f8c"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/intro",
                component: ComponentCreator("/next/intro", "0b4"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/auth/client-sdk",
                component: ComponentCreator("/next/modules/auth/client-sdk", "866"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/auth/overview",
                component: ComponentCreator("/next/modules/auth/overview", "91f"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/auth/server-setup",
                component: ComponentCreator("/next/modules/auth/server-setup", "514"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/auth/troubleshooting",
                component: ComponentCreator("/next/modules/auth/troubleshooting", "cf6"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/email/overview",
                component: ComponentCreator("/next/modules/email/overview", "794"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/email/providers",
                component: ComponentCreator("/next/modules/email/providers", "087"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/email/template-management",
                component: ComponentCreator("/next/modules/email/template-management", "dc5"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/logging/overview",
                component: ComponentCreator("/next/modules/logging/overview", "3d5"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/logging/quickstart",
                component: ComponentCreator("/next/modules/logging/quickstart", "8e2"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/logging/sinks",
                component: ComponentCreator("/next/modules/logging/sinks", "b79"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/rbac/examples",
                component: ComponentCreator("/next/modules/rbac/examples", "8e9"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/rbac/overview",
                component: ComponentCreator("/next/modules/rbac/overview", "208"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/modules/rbac/policy-model",
                component: ComponentCreator("/next/modules/rbac/policy-model", "cb9"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/platform-admin/portal-overview",
                component: ComponentCreator("/next/platform-admin/portal-overview", "b7c"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/platform-admin/sdk-guide",
                component: ComponentCreator("/next/platform-admin/sdk-guide", "3b1"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/api/auth",
                component: ComponentCreator("/next/reference/api/auth", "eaa"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/api/email",
                component: ComponentCreator("/next/reference/api/email", "3b9"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/api/logging",
                component: ComponentCreator("/next/reference/api/logging", "ccb"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/api/rbac",
                component: ComponentCreator("/next/reference/api/rbac", "9a3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/architecture",
                component: ComponentCreator("/next/reference/architecture", "3f7"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/reference/cli",
                component: ComponentCreator("/next/reference/cli", "588"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/sdk-integration/configuration",
                component: ComponentCreator("/next/sdk-integration/configuration", "a52"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/sdk-integration/examples/browser",
                component: ComponentCreator("/next/sdk-integration/examples/browser", "2db"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/sdk-integration/examples/node",
                component: ComponentCreator("/next/sdk-integration/examples/node", "f5f"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/sdk-integration/installation",
                component: ComponentCreator("/next/sdk-integration/installation", "a98"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/next/sdk-integration/overview",
                component: ComponentCreator("/next/sdk-integration/overview", "2f3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
            ],
          },
        ],
      },
      {
        path: "/",
        component: ComponentCreator("/", "123"),
        routes: [
          {
            path: "/",
            component: ComponentCreator("/", "395"),
            routes: [
              {
                path: "/getting-started/faqs",
                component: ComponentCreator("/getting-started/faqs", "303"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/getting-started/prerequisites",
                component: ComponentCreator("/getting-started/prerequisites", "d9b"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/getting-started/quickstart",
                component: ComponentCreator("/getting-started/quickstart", "e92"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/intro",
                component: ComponentCreator("/intro", "794"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/auth/client-sdk",
                component: ComponentCreator("/modules/auth/client-sdk", "f60"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/auth/overview",
                component: ComponentCreator("/modules/auth/overview", "602"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/auth/server-setup",
                component: ComponentCreator("/modules/auth/server-setup", "e11"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/auth/troubleshooting",
                component: ComponentCreator("/modules/auth/troubleshooting", "a90"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/email/overview",
                component: ComponentCreator("/modules/email/overview", "571"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/email/providers",
                component: ComponentCreator("/modules/email/providers", "4df"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/email/template-management",
                component: ComponentCreator("/modules/email/template-management", "c89"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/logging/overview",
                component: ComponentCreator("/modules/logging/overview", "6b5"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/logging/quickstart",
                component: ComponentCreator("/modules/logging/quickstart", "267"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/logging/sinks",
                component: ComponentCreator("/modules/logging/sinks", "c62"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/rbac/examples",
                component: ComponentCreator("/modules/rbac/examples", "7ae"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/rbac/overview",
                component: ComponentCreator("/modules/rbac/overview", "334"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/modules/rbac/policy-model",
                component: ComponentCreator("/modules/rbac/policy-model", "a23"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/platform-admin/portal-overview",
                component: ComponentCreator("/platform-admin/portal-overview", "b30"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/platform-admin/sdk-guide",
                component: ComponentCreator("/platform-admin/sdk-guide", "e35"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/api/auth",
                component: ComponentCreator("/reference/api/auth", "17a"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/api/email",
                component: ComponentCreator("/reference/api/email", "d66"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/api/logging",
                component: ComponentCreator("/reference/api/logging", "dc1"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/api/rbac",
                component: ComponentCreator("/reference/api/rbac", "1d9"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/architecture",
                component: ComponentCreator("/reference/architecture", "add"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/reference/cli",
                component: ComponentCreator("/reference/cli", "fea"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/sdk-integration/configuration",
                component: ComponentCreator("/sdk-integration/configuration", "434"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/sdk-integration/examples/browser",
                component: ComponentCreator("/sdk-integration/examples/browser", "b6a"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/sdk-integration/examples/node",
                component: ComponentCreator("/sdk-integration/examples/node", "1a3"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/sdk-integration/installation",
                component: ComponentCreator("/sdk-integration/installation", "934"),
                exact: true,
                sidebar: "defaultSidebar",
              },
              {
                path: "/sdk-integration/overview",
                component: ComponentCreator("/sdk-integration/overview", "593"),
                exact: true,
                sidebar: "defaultSidebar",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    path: "*",
    component: ComponentCreator("*"),
  },
];
